package diagnostics

import (
	"bufio"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"time"

	"github.com/yowainwright/pre/internal/fileutil"
)

type Summary struct {
	Enabled  bool   `json:"enabled"`
	Events   int    `json:"events"`
	Included int    `json:"included_events,omitempty"`
	Invalid  int    `json:"invalid"`
	Bytes    int64  `json:"bytes"`
	MaxBytes int64  `json:"max_bytes"`
	Rotated  bool   `json:"rotated"`
	Oldest   string `json:"oldest,omitempty"`
	Newest   string `json:"newest,omitempty"`
}

type Report struct {
	SchemaVersion int      `json:"pre.schema_version"`
	GeneratedAt   string   `json:"generated_at"`
	Since         string   `json:"since,omitempty"`
	Privacy       []string `json:"privacy"`
	Summary       Summary  `json:"summary"`
	Events        []Event  `json:"events"`
}

func Status() (Summary, error) {
	_, summary, err := readEvents(time.Time{}, 0)
	return summary, err
}

func Events(since time.Time, limit int) ([]Event, Summary, error) {
	events, summary, err := readEvents(since, limit)
	return events, summary, err
}

func Export(since time.Time) (string, Summary, error) {
	events, summary, err := readEvents(since, 0)
	if err != nil {
		return "", summary, err
	}
	report := newReport(since, summary, events)
	path, err := writeReport(report)
	return path, summary, err
}

func Clear() error {
	dir, err := stateDir()
	if err != nil {
		return err
	}
	for _, path := range eventPaths(dir) {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	return nil
}

func readEvents(since time.Time, limit int) ([]Event, Summary, error) {
	dir, err := stateDir()
	summary := Summary{Enabled: Enabled(), MaxBytes: maxBytes}
	if err != nil {
		return nil, summary, err
	}
	events, err := readEventFiles(dir, since, &summary)
	events = limitEvents(events, limit)
	summary.Included = len(events)
	return events, summary, err
}

func readEventFiles(dir string, since time.Time, summary *Summary) ([]Event, error) {
	events := []Event{}
	for _, path := range eventPaths(dir) {
		fileEvents, err := readEventFile(path, since, summary)
		if err != nil {
			return events, err
		}
		events = append(events, fileEvents...)
	}
	return events, nil
}

func readEventFile(path string, since time.Time, summary *Summary) ([]Event, error) {
	info, err := os.Stat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	summary.Bytes += info.Size()
	summary.Rotated = summary.Rotated || filepath.Base(path) == rotatedFile
	return scanEventFile(path, since, summary)
}

func scanEventFile(path string, since time.Time, summary *Summary) ([]Event, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 4096), 1<<20)
	events := []Event{}
	for scanner.Scan() {
		event, ok := decodeEvent(scanner.Bytes(), summary)
		if ok && eventInRange(event, since) {
			events = append(events, event)
		}
	}
	return events, scanner.Err()
}

func decodeEvent(line []byte, summary *Summary) (Event, bool) {
	var event Event
	if err := json.Unmarshal(line, &event); err != nil {
		summary.Invalid++
		return nil, false
	}
	summary.Events++
	trackEventTimes(event, summary)
	return event, true
}

func eventInRange(event Event, since time.Time) bool {
	if since.IsZero() {
		return true
	}
	eventTime, ok := eventTime(event)
	return ok && !eventTime.Before(since)
}

func eventTime(event Event) (time.Time, bool) {
	value, ok := event["time"].(string)
	if !ok {
		return time.Time{}, false
	}
	parsed, err := time.Parse(time.RFC3339Nano, value)
	return parsed, err == nil
}

func trackEventTimes(event Event, summary *Summary) {
	eventTime, ok := eventTime(event)
	if !ok {
		return
	}
	formatted := eventTime.UTC().Format(time.RFC3339)
	if summary.Oldest == "" || formatted < summary.Oldest {
		summary.Oldest = formatted
	}
	if summary.Newest == "" || formatted > summary.Newest {
		summary.Newest = formatted
	}
}

func limitEvents(events []Event, limit int) []Event {
	if limit <= 0 || len(events) <= limit {
		return events
	}
	return events[len(events)-limit:]
}

func newReport(since time.Time, summary Summary, events []Event) Report {
	return Report{
		SchemaVersion: SchemaVersion,
		GeneratedAt:   nowFn().UTC().Format(time.RFC3339Nano),
		Since:         sinceLabel(since),
		Privacy:       privacyNotes(),
		Summary:       summary,
		Events:        events,
	}
}

func sinceLabel(since time.Time) string {
	if since.IsZero() {
		return "all"
	}
	return since.UTC().Format(time.RFC3339)
}

func privacyNotes() []string {
	return []string{
		"Local report generated by explicit user command.",
		"No command text, full arguments, paths, environment variables, package names by default, OSV response bodies, prompts, completions, or plugin contents are recorded.",
	}
}

func writeReport(report Report) (string, error) {
	dir, err := stateDir()
	if err != nil {
		return "", err
	}
	reportDir := filepath.Join(dir, reportsDir)
	if err := os.MkdirAll(reportDir, 0700); err != nil {
		return "", err
	}
	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return "", err
	}
	path := filepath.Join(reportDir, "pre-diagnostics-"+nowFn().UTC().Format("20060102T150405Z")+".json")
	return path, fileutil.AtomicWriteFile(path, data, 0600)
}
